version: "2"
services:
  tasker:
    build: .
    image: tasker
    expose:
     - 8080
    ports:
     - 8090:8080
    links:
     - mongo
    environment:
      GITHUB_CLIENT_ID: 77f0c1f303d2e8c07120
      GITHUB_CLIENT_SECRET: e78b87862c0fd46e50e351ce0307b4eadca9167c
      MONGO_URL: mongodb://mongo/tasker      
      PORT: 8080
  mongo:
    image: mongo
    expose:
      - 27017

